Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(kawasaki.py:1569034): Gdk-CRITICAL **: 19:13:22.677: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
